### ISSUE TITLE
刚运行就报错，管理员权限运行

### ISSUE THREAD

**Issue by SENyiAi** [angelof13/starRailScript#8]
PS C:\Users\Administrator> python C:\Users\Administrator\Desktop\starRailScript-main\starRail.py
Select Window
(620, 35, 2562, 1171)
correct coordinates
[740, 1028, 30, 15]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\starRailScript-main\starRail.py", line 90, in <module>
    pa.screenshot("data/fightMarker.png",region=(cfg.nMC['fightMarker'][0],cfg.nMC['fightMarker'][1],cfg.nMC['fightMarker'][2],cfg.nMC['fightMarker'][3])) #截取Enter部分，以便确认是否战斗状态
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyscreeze\__init__.py", line 544, in _screenshot_win32
    im.save(imageFilename)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\PIL\Image.py", line 2435, in save
    fp = builtins.open(filename, "w+b")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/fightMarker.png'
PS C:\Users\Administrator>

**Comment by angelof13** [comment]
您是用vscode运行的吗？
假如您是用VScode打开运行，请麻烦在vscode的左上角，file > open folder 选择打开文件夹到starRailScript-main文件夹中，能看到data文件夹，然后打开data目录的上级目录，类似于下面的样子，再重新运行下试试
![屏幕截图 2023-12-27 151507](https://github.com/angelof13/starRailScript/assets/19170749/6f0727b2-f171-4b46-962f-7c2c358cd79a)
